#!/usr/bin/env python3

"""
Game of Thrones chapters vs episodes chart generator
Copyright (c) 2013-2018, Joel Geddert

This script generates an HTML file of the table.

Software License:
	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.

A note from the author:
	The original chart generated by this code, as well as all remaining applicable
	source & asset files (except where noted), are licensed under a Creative Commons
	BY-SA 4.0 license <http://creativecommons.org/licenses/by-sa/4.0/>. If you are
	going to use any of this code to create a derivative work, please respect this
	CC license.
"""

##### Imports #####


import argparse

from utils import *
from book_show_types import *
import parsing
import printing


##### Hard-coded variables and other runtime parameters #####

_copyrightInfo = "(c) 2013-2018 Joel Geddert"


##### Processing starts here #####


def main():
	parser = argparse.ArgumentParser()
	parser.add_argument('-d', '--debug', action='store_true')
	args = parser.parse_args()

	set_debug(args.debug)

	print("")
	print("Game of Thrones episode-chapter table generator")
	print(_copyrightInfo)
	print("")

	db = parsing.do_parsing()

	print("")

	print("Sanity checking data")
	db.sanity_check()

	print("")

	printing.do_printing(db)

	print("")

	if warnings:
		print("Complete, with warnings:")
		for warning in warnings:
			print(warning)

	else:
		print("Success!")


if __name__ == "__main__":
	main()
